//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCuentasGoogle
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosGoogle
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string PasswordHashFunction { get; set; }
        public string OrgUnitPath { get; set; }
        public string NewPrimaryEmail { get; set; }
        public string RecoveryEmail { get; set; }
        public string HomeSecondaryEmail { get; set; }
        public string WorkSecondaryEmail { get; set; }
        public string RecoveryPhone { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string WorkAddress { get; set; }
        public string HomeAddress { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeType { get; set; }
        public string EmployeeTitle { get; set; }
        public string ManagerEmail { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string BuildingID { get; set; }
        public string FloorName { get; set; }
        public string FloorSection { get; set; }
        public string ChangePasswordAtNextSignIn { get; set; }
        public string NewStatus { get; set; }
    }
}
